name: Bug de producto
description: Reportar un bug de alguno de mis productos
title: BUG -
labels:
    - bug
body:
    - type: dropdown
    id: producto
    attributes:
      label: A que producto pertenece
      description: Elegi uno de la lista
      options:
                - Producto 1
                - Producto 2
                - Producto 3
                - Producto 4
                - Producto 5
    validations:
      required: true
    - type: textarea
    id: descripcion
    attributes:
      label: Que paso
      description: Describe el error
    validations:
      required: true
    - type: textarea
    id: esperado
    attributes:
      label: Que esperabas que pase
      description: Opcional
