name: "🐛 Bug de producto"
description: "Reportar un bug de alguno de mis productos"
title: "[BUG] "
labels: ["type: bug"]
body:
    - type: dropdown
    id: producto
    attributes:
      label: "¿A qué producto pertenece? *"
      description: "Elegí uno, es obligatorio"
      options:
                - Producto 1
                - Producto 2
                - Producto 3
                - Producto 4
                - Producto 5
    validations:
      required: true

    - type: textarea
    id: que-paso
    attributes:
      label: ¿Qué pasó?
      placeholder: Explica el error
    validations:
      required: true

    - type: textarea
    id: esperado
    attributes:
      label: ¿Qué esperabas que pase?
